Vagrant::Config.run do |config|
    config.vm.define :frontend do |inner_config|
        inner_config.vm.box = "precise64"
        inner_config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
        inner_config.vm.forward_port("http", 80, 8080)
        inner_config.vm.network("33.33.33.33")
    end

    config.vm.define :backend do |inner_config|
        inner_config.vm.box = "precise64"
        inner_config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
        inner_config.vm.forward_port("http", 80, 8081)
        inner_config.vm.network("33.33.33.34")
    end

end
