Vagrant::Config.run do |config|

    config.vm.define :server do |inner_config|
        inner_config.vm.box = "lucid64"
        inner_config.vm.box_url = 'http://files.vagrantup.com/lucid64.box'
        inner_config.vm.forward_port("http", 80, 8080)
        inner_config.vm.network("33.33.33.33")
    end

end
